"""Discover GPU hardware profiler aliases and optional scaled seed for DVFS demos."""

from __future__ import annotations

import csv
import logging
import os
import re
import shutil
from typing import List, Optional, Tuple

logger = logging.getLogger(__name__)

_TIME_US_COLS = {"time_us", "latency_us"}
_SYNTHETIC_MARKER = ".synthetic_profile"
_V100_MHZ_RE = re.compile(r"^V100(?:_(?P<mhz>\d+)MHz)?$")
# Stock V100 profile tag (no _MHz suffix) sits between 900 and 1100 MHz bundles.
_V100_BASE_MHZ = 1000


def _profiler_perf_root() -> str:
    """Resolve profiler/perf from repo root or astra-sim cwd."""
    candidates = (
        os.path.join(os.path.dirname(__file__), "..", "..", "profiler", "perf"),
        "profiler/perf",
        "../profiler/perf",
    )
    for path in candidates:
        abspath = os.path.abspath(path)
        if os.path.isdir(abspath):
            return abspath
    return os.path.abspath(candidates[0])


def _v0_perf_root() -> str:
    candidates = (
        os.path.join(os.path.dirname(__file__), "..", "..", "profiler", "v0", "perf_models"),
        "profiler/v0/perf_models",
        "../profiler/v0/perf_models",
    )
    for path in candidates:
        abspath = os.path.abspath(path)
        if os.path.isdir(abspath):
            return abspath
    return os.path.abspath(candidates[0])


def discover_hardware_for_model(model: str, variant: str = "bf16") -> List[str]:
    """Hardware names with profiler/perf/{hw}/{model}/{variant}/."""
    root = _profiler_perf_root()
    if not os.path.isdir(root):
        return []
    found = []
    for hw in sorted(os.listdir(root)):
        if os.path.isdir(os.path.join(root, hw, model, variant)):
            found.append(hw)
    return found


def _v100_mhz_key(hardware: str) -> Optional[int]:
    match = _V100_MHZ_RE.match(hardware)
    if not match:
        return None
    mhz = match.group("mhz")
    return int(mhz) if mhz else _V100_BASE_MHZ


def _v100_dvfs_pair(discovered: List[str], primary: str) -> Optional[Tuple[str, str]]:
    """Pick the farthest clock profile for layer-wise V100 DVFS alternation."""
    v100s = [hw for hw in discovered if _v100_mhz_key(hw) is not None]
    if len(v100s) < 2:
        return None
    if primary not in v100s:
        ordered = sorted(v100s, key=_v100_mhz_key)
        return ordered[0], ordered[-1]
    primary_mhz = _v100_mhz_key(primary)
    others = [hw for hw in v100s if hw != primary]
    farthest = max(others, key=lambda hw: abs(_v100_mhz_key(hw) - primary_mhz))
    return primary, farthest


def _discover_v0_hardware_for_model(model: str) -> List[str]:
    root = _v0_perf_root()
    if not os.path.isdir(root):
        return []
    found = []
    for hw in sorted(os.listdir(root)):
        if os.path.isfile(os.path.join(root, hw, model, "tp1", "layers.csv")):
            found.append(hw)
    return found


def _scale_csv_times(path: str, scale: float) -> None:
    if not os.path.isfile(path):
        return
    rows = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            return
        fieldnames = list(reader.fieldnames)
        time_col = next((c for c in fieldnames if c in _TIME_US_COLS or c.endswith("_us")), None)
        if time_col is None:
            return
        for row in reader:
            try:
                row[time_col] = str(float(row[time_col]) * scale)
            except (TypeError, ValueError, KeyError):
                pass
            rows.append(row)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def seed_scaled_hardware_alias(
    source_hw: str,
    target_hw: str,
    model: str,
    variant: str = "bf16",
    scale: float = 1.25,
) -> bool:
    """Copy profiler/perf source_hw -> target_hw with scaled layer timings."""
    src = os.path.join(_profiler_perf_root(), source_hw, model, variant)
    dst = os.path.join(_profiler_perf_root(), target_hw, model, variant)
    if os.path.isdir(dst):
        return True
    if not os.path.isdir(src):
        return False
    shutil.copytree(src, dst)
    meta_path = os.path.join(dst, "meta.yaml")
    if os.path.isfile(meta_path):
        with open(meta_path) as f:
            text = f.read()
        text = text.replace(f"hardware: {source_hw}", f"hardware: {target_hw}")
        # Mark unmistakably as synthetic so it can never pass as measured data.
        text += (
            f"\n# SYNTHETIC PROFILE — fabricated, NOT measured on real hardware.\n"
            f"# Generated by seed_scaled_hardware_alias from {source_hw} x{scale}.\n"
            f"synthetic: true\n"
            f"synthetic_seeded_from: {source_hw}\n"
            f"synthetic_scale: {scale}\n"
        )
        with open(meta_path, "w") as f:
            f.write(text)
    # Sentinel file too, in case meta.yaml is absent.
    with open(os.path.join(dst, _SYNTHETIC_MARKER), "w") as f:
        f.write(f"seeded_from={source_hw}\nscale={scale}\n")
    for root, _, files in os.walk(dst):
        for name in files:
            if name.endswith(".csv"):
                _scale_csv_times(os.path.join(root, name), scale)
    logger.warning(
        "Seeded SYNTHETIC hardware alias %s from %s (scale=%.2f) for %s/%s — "
        "fabricated data, not measured.",
        target_hw, source_hw, scale, model, variant,
    )
    return True


def is_synthetic_profile(hardware, model, variant="bf16"):
    """True if profiler/perf/<hardware>/<model>/<variant> was fabricated by seeding."""
    base = os.path.join(_profiler_perf_root(), hardware, model, variant)
    if os.path.isfile(os.path.join(base, _SYNTHETIC_MARKER)):
        return True
    meta = os.path.join(base, "meta.yaml")
    if os.path.isfile(meta):
        try:
            with open(meta) as f:
                for line in f:
                    s = line.strip()
                    if s.startswith("synthetic:"):
                        return s.split(":", 1)[1].strip().lower() in ("true", "yes", "1")
        except OSError:
            pass
    return False


def resolve_hardware_pair(
    model: str,
    variant: str,
    primary: str,
    alt: Optional[str] = None,
    allow_synthetic: bool = False,
) -> Tuple[str, str]:
    """Return (hw_a, hw_b) for layer-boundary hardware alternation.

    By default only **measured** profiler/perf profiles are used. When the caller
    requests an explicit ``alt`` hardware, its profile must exist and be real;
    otherwise a clear error is raised. Fabricating a scaled placeholder profile
    only happens when ``allow_synthetic=True`` (and the result is marked synthetic).
    """
    def _exists(hw: str) -> bool:
        return os.path.isdir(os.path.join(_profiler_perf_root(), hw, model, variant))

    # Explicit pairing requested: never silently substitute synthetic data.
    if alt is not None and alt != primary:
        if _exists(alt):
            if is_synthetic_profile(alt, model, variant) and not allow_synthetic:
                raise FileNotFoundError(
                    f"Requested hardware-alt '{alt}' for {model}/{variant} is a SYNTHETIC "
                    f"(fabricated) profile, not measured. Profile that GPU for real, or pass "
                    f"--dvfs-allow-synthetic-profiles to use the scaled placeholder."
                )
            return primary, alt
        if allow_synthetic and seed_scaled_hardware_alias(primary, alt, model, variant) and _exists(alt):
            return primary, alt
        raise FileNotFoundError(
            f"No profiler/perf profile for requested hardware-alt '{alt}' ({model}/{variant}). "
            f"Profile that GPU, or pass --dvfs-allow-synthetic-profiles to fabricate a scaled "
            f"placeholder."
        )

    # Auto-discover a second profile — measured only, unless synthetic is allowed.
    discovered = [
        hw for hw in discover_hardware_for_model(model, variant)
        if allow_synthetic or not is_synthetic_profile(hw, model, variant)
    ]
    v100_pair = _v100_dvfs_pair(discovered, primary)
    if v100_pair is not None:
        return v100_pair
    if primary in discovered:
        others = [h for h in discovered if h != primary]
        if others:
            return primary, others[0]
    if len(discovered) >= 2:
        return discovered[0], discovered[1]

    if allow_synthetic:
        for candidate in _discover_v0_hardware_for_model(model):
            if candidate != primary:
                if seed_scaled_hardware_alias(primary, candidate, model, variant):
                    return primary, candidate

    return primary, primary


def toggle_hardware(pair: Tuple[str, str], current: str) -> Tuple[str, str]:
    """Swap to the other hardware in a 2-GPU pair. Returns (old, new)."""
    other = pair[1] if current == pair[0] else pair[0]
    return current, other
